import { writeFileSync } from 'fs';

/**
 * Parses the complete FormareMedicala.ro protocol list (390 protocols)
 * provided by the user and creates a structured JSON file
 */

const rawList = `J05AX28    BULEVIRTIDUM
J07AL02    VACCIN PNEUMOCOCIC POLIZAHARIDIC
J05AX18    LETERMOVIRUM (forma orală)
A10BD20    COMBINAȚII EMPAGLIFLOZINUM + METFORMINUM
A10BD24    COMBINAȚII ERTUGLIFLOZINUM + SITAGLIPTINUM
A10BJ02    LIRAGLUTIDUM
A10BK01    DAPAGLIFLOZINUM
A10BK01-03    INSUFICIENTA CARDIACA CRONICA (DAPAGLIFLOZINUM,EMPAGLIFLOZINUM)
B06AC04    CONESTAT ALFA
B06AC05    LANADELUMABUM
D11AH-L04AA    DERMATITA ATOPICĂ - AGENŢI BIOLOGICI: DUPILUMABUM**1Ω ȘI INHIBITORI DE JAK: BARICITINIBUM**1Ω
J02AC05    ISAVUCONAZOLUM
L01EJ02    FEDRATINIBUM
L01EK03    TIVOZANIBUM
L03AB15    ROPEGINTERFERON ALFA-2B
L04AA26-51    LUPUS ERITEMATOS SISTEMIC - AGENŢI BIOLOGICI: BELIMUMABUM**1, ANIFROLUMABUM**1
N05AX15    CARIPRAZINUM
N06AX26    VORTIOXETINUM
R03AL09    BECLOMETASONUM+FORMOTEROLUM+GLICOPIRONIU BROMIDUM
R03AL11    FORMOTEROLUM+GLICOPIRONIUM+BUDESONIDUM
R03DX05-UCS    URTICARIE CRONICĂ SPONTANĂ – TERAPIE BIOLOGICĂ
A001E    ORLISTATUM
A002C    PALONOSETRONUM
A004C    ONDASETRONUM, GRANISETRONUM
A005E    PARICALCITOLUM
A006E    CALCITRIOLUM
A008E    IMIGLUCERASUM
A010N    COMPLEX DE HIDROXID FER (III) SUCROZĂ
A014E    AGALSIDASUM BETA
A015E    INSULINUM LISPRO
A016E    INSULINUM ASPART
A017E    INSULINUM LISPRO
A018E    INSULINUM ASPART
A019E    INSULINUM GLULIZINA
A020E    PIOGLITAZONUM
A021E    ACIDUM TIOCTICUM (ALFA-LIPOICUM)
A022E    SITAGLIPTINUM
A023E    INSULINUM DETEMIR
A024E    INSULINUM GLARGINE
A025E    COMBINAŢII (PIOGLITAZONUM + METFORMIN)
A029E    INSULINUM LISPRO
A030Q    AGLUCOSIDASUM ALFA
A04AA55    COMBINAȚII (NETUPITANTUM + PALONOSETRONUM)
A05AA04    ACID OBETICHOLICUM
A09AA02    PANCREATINUM (concentraţia 35.000 U FE)
A10AD06    COMBINAȚII INSULINUM DEGLUDEC + INSULINUM ASPART
A10AE06    INSULINUM DEGLUDEC
A10AE54    COMBINATII (INSULINE GLARGINE+LIXISENATIDUM)
A10AE56    COMBINATII INSULINUM DEGLUDEC+LIRAGLUTIDUM
A10BD07    COMBINAŢII (SITAGLIPTINUM + METFORMINUM)
A10BD08    COMBINAȚII (VILDAGLIPTIN+METFORMIN)
A10BD10    COMBINAŢII (SAXAGLIPTINUM + METFORMINUM) - concentraţia 2,5 mg/1000 mg
A10BD15    COMBINAȚII (DAPAGLIFLOZINUM + METFORMINUM)
A10BD21    COMBINAȚII (SAXAGLIPTIN+DAPAGLIFLOZINUM)
A10BH02    VILDAGLIPTINUM
A10BH03    SAXAGLIPTINUM
A10BJ01    EXENATIDUM
A10BJ05    DULAGLUTIDUM
A10BJ06    SEMAGLUTIDUM
A10BK03    EMPAGLIFLOZINUM
A10BX09    DAPAGLIFLOZINUM
A10BX10    LIXISENATIDUM
A11DA03    BENFOTIAMINUM
A11DBN1    COMBINATII
A16AA04    MERCAPTAMINUM
A16AA07    METRELEPTINUM
A16AB03    AGALSIDASUM ALFA
A16AB09    IDURSULFASE
A16AB10    VELAGLUCERASE ALFA
A16AB12    ELOSULFASE ALFA
A16AB15    VELMANAZA ALFA
A16AB17    CERLIPONASUM ALFA
A16AB25    OLIPUDASE ALFA
A16AX03    NATRII PHENYLBUTYRATE
A16AX06    MIGLUSTAT
A16AX07    PLERIXAFOR
A16AX07S    SAPROPTERINUM
A16AX08    TEDUGLUTIDUM
A16AX09    GLYCEROLI PHENYLBUTYRAS
A16AX10    ELIGLUSTAT
A16AX14    MIGALASTATUM
A16AX16    GIVOSIRAN
A16AX18    LUMASIRANUM
AE01E    PROTOCOL TERAPEUTIC ÎN DIABETUL ZAHARAT
B008D    PROTOCOL PENTRU PROFILAXIA ŞI TRATAMENTUL TROMBOEMBOLISMULUI VENOS ÎN AMBULATOR
B009I    CLOPIDOGRELUM
B009N    EPOETINUM BETA
B010N    EPOETINUM ALFA
B011N    DARBEPOETINUM ALFA
B013K    MEDICAŢIA ADJUVANTĂ TERAPIEI ANTIVIRALE ÎN HEPATITE CRONICE (FILGRASTIM)
B014I    SULODEXIDUM
B015D    EPTACOG ALFA ACTIVATUM
B016I    DIOSMINUM
B01AC21-HTAP    TREPROSTINILUM
B01AC21-HTAPC    TREPROSTINILUM
B01AC24    TICAGRELOR
B01AC27    SELEXIPAGUM
B01AE-B01AF    ANTICOAGULANTE ORALE NON-ANTI VITAMINA K (NOAC)
B01AX07    CAPLACIZUMABUM
B02AB02    INHIBITOR ALFA 1 PROTEINAZA UMANA
B02BD02    RURIOCTOCOG ALFA PEGOL
B02BD02-Turocto    TUROCTOCOG ALFA PEGOL
B02BD14    SUSOCTOCOG ALFA
B02BX04    ROMIPLOSTINUM
B02BX05    ELTROMBOPAG
B02BX05-AAS    ELTROMBOPAG
B02BX06    EMICIZUMAB
B03XA03    EPOETINUM ZETA
B03XA03M    METOXI-POLIETILENGLICOL EPOETIN BETA
B03XA06    LUSPATERCEPT
B03XA06-SMD    LUSPATERCEPT
B06AC01    INHIBITOR DE ESTERAZĂ C1, UMANĂ
B06AC02    ICATIBANTUM
BD01D    HEMOFILIA A si B si BOALA VON WILLEBRAND
C002I    ALPROSTADILUM
C003I    IVABRADINUM
C004I    ACID OMEGA-3-ESTERI ETILICI
C005I    SARTANI ÎN INSUFICIENŢA CARDIACĂ
C008N    IRBESARTANUM
C02KX02    TAFAMIDIS
C03XA01    TOLVAPTAN
C07AA05    PROPRANOLOLUM (soluție orală)
C07FX05    COMBINAȚII (METOPROLOLUM + IVABRADINUM)
C09BB02    COMBINAȚII (ENALAPRILUM+LERCANIDIPINUM)
C09DB05    COMBINAȚII (IRBESARTANUM+AMLODIPINUM)
C09DX04    SACUBITRILUM/VALSARTANUM
C10AX13    EVOLOCUMAB
C10AX14    ALIROCUMABUM
C10BA05    COMBINAŢII (EZETIMIBUM + ATORVASTATINUM)
C10BA06    COMBINAȚII (ROSUVASTATINUM + EZETIMIBUM)
C10BX13    COMBINAŢII (ROSUVASTATINUM + PERINDOPRILUM + INDAPAMIDUM)
CI01I    BOSENTANUM
CI01I-HTP    Protocol terapeutic în hipertensiunea arterială pulmonară: SILDENAFILUM, BOSENTANUM, AMBRISENTANUM, MACITENTANUM, RIOCIGUAT
D002L    ACITRETINUM
D11AH05-A    DUPILUMABUM
G001C    CABERGOLINUM
G002N    ESTRADIOLUM VALERAT + DIENOGEST
G003N    FOLLITROPINUM ALFA
G004N    GANIRELIXUM
G005N    LEVONORGESTRELUM
G006N    LUTROPINA ALFA
G007N    TIBOLONUM
G008N    FOLLITROPINUM BETA
G009N    SOLIFENACINUM SUCCINAT
G010N    TOLTERODINUM/SOLIFENACINUM
H003N    CINACALCET HIDROCLORID
H004E    CETRORELIXUM
H005E    PROTOCOL TERAPEUTIC ÎN ACROMEGALIE ŞI GIGANTISM
H006C    TUMORI NEUROENDOCRINE - TRATAMENT CU ANALOGI DE SOMATOSTATINĂ
H006E    DCI SOMATROPINUM LA COPII, ÎN PERIOADA DE TRANZIŢIE ȘI LA ADULȚI CU DEFICIT AL HORMONULUI DE CREȘTERE
H011Q    SOMATROPINUM
H01AC03    MECASERMINUM
H01CB05    PASIREOTIDUM
H05AA02    TERIPARATIDUM
H05AA03    PARATHYROID HORMONE
J001G    IMUNOGLOBULINĂ NORMALĂ PENTRU ADMINISTRARE INTRAVASCULARĂ
J002N    RIBAVIRINUM
J003N    PEGINTERFERONUM ALFA 2B
J004N    PEGINTERFERONUM ALFA 2A
J005N    LAMIVUDINUM
J006N    INTERFERONUM ALFA 2B
J007N    INTERFERONUM ALFA 2A
J008N    ENTECAVIRUM
J009N    ADEFOVIRUM DIPIVOXILUM
J010D    CASPOFUNGINUM
J012B    VORICONAZOLUM
J01XB01    COLISTIMETAT DE SODIU
J02AB02    KETOCONAZOLUM (comprimate 200 MG)
J05AP    Hepatită cronică şi Ciroză hepatică cu VHC, cu medicamente cu acțiune antivirală directă (interferon-free)
J05AP56    SOFOSBUVIRUM+VELPATASVIRUM+VOXILAPREVIRUM
J06BA01    IMUNOGLOBULINA UMANA NORMALA
J06BB16    PALIVIZUMABUM
J07AH08-09    VACCIN MENINGOCOCIC
J07AJ52    VACCIN DIFTERO-TETANO-PERTUSSIS ACELULAR
J07BB02-03    VACCIN GRIPAL
J07BC01    VACCIN HEPATITIC B
J07BD52    VACCIN RUJEOLIC, RUBEOLIC, URLIAN (ROR)
J07BK01    VACCIN VARICELIC VIU ATENUAT
J07BM03    VACCIN PAPILOMAVIRUS
L001C    ACIDUM CLODRONICUM
L001G    MITOXANTRONUM
L002G    SCLEROZA MULTIPLĂ - TRATAMENT IMUNOMODULATOR
L004C    BEVACIZUMABUM
L008C    IMATINIBUM
L012C    BORTEZOMIBUM
L014AE    FIBROZA PULMONARĂ IDIOPATICĂ
L014C    RITUXIMABUM (original si biosimilar)
L015D    ANAGRELIDUM
L016C    INTERFERON ALFA 2B
L01AA09    BENDAMUSTINUM
L01BB06    CLOFARABINUM
L01BB07    NELARABINUM
L01BC07    AZACITIDINUM
L01BC08    DECITABINUM
L01BC59    COMBINATI (TRIFLURIDINUM + TIPIRACILUM)
L01CD01    PACLITAXELUM (concentrația 5 mg/ml)
L01CD04    CABAZITAXELUM
L01CX01    TRABECTEDINUM
L01EA06    ASCIMINIBUM
L01ED04    BRIGATINIBUM
L01EE04    SELUMETINIB
L01EH03    TUCATINIBUM
L01EL02    ACALABRUTINIBUM
L01FA01    RITUXIMABUM
L01FD04    TRASTUZUMABUM DERUXTECANUM
L01FF-L01EX    DCI NIVOLUMABUM + DCI CABOZANTINIBUM
L01FX02    GEMTUZUMAB OZOGAMICIN
L01FX09    MOGAMULIZUMAB
L01FX17    SACITUZUMAB GOVITECAN
L01FX25    MOSUNETUZUMABUM
L01XC02    RITUXIMABUM
L01XC08    PANITUMUMABUM
L01XC10    OFATUMUMAB
L01XC11    IPILIMUMABUM
L01XC11-17    DCI NIVOLUMABUM + DCI IPILIMUMABUM
L01XC12    BRENTUXIMAB VEDOTIN
L01XC13    PERTUZUMABUM
L01XC14    TRASTUZUMAB EMTANSINE
L01XC15    OBINUTUZUMAB
L01XC16    DINUTUXIMAB BETA
L01XC17    NIVOLUMABUM
L01XC18    PEMBROLIZUMABUM
L01XC19    BLINATUMOMABUM
L01XC21    RAMUCIRUMABUM
L01XC24    DARATUMUMABUM
L01XC26    INOTUZUMAB OZOGAMICIN
L01XC28    DURVALUMABUM
L01XC31    AVELUMABUM
L01XC32    ATEZOLIZUMABUM
L01XC33    CEMIPLIMABUM
L01XC37    POLATUZUMAB VEDOTIN
L01XE02    GEFITINIBUM
L01XE06    DASATINIB
L01XE07    LAPATINIBUM
L01XE08    NILOTINIBUM
L01XE10    EVEROLIMUS (VOTUBIA)
L01XE10A    EVEROLIMUS
L01XE11    PAZOPANIBUM
L01XE12    VANDETANIBUM
L01XE13    AFATINIBUM
L01XE14    BOSUTINIBUM
L01XE15    VEMURAFENIBUM
L01XE16    CRIZOTINIBUM
L01XE17    AXITINIBUM
L01XE18    RUXOLITINIBUM
L01XE21    REGORAFENIBUM
L01XE23    DABRAFENIBUM
L01XE23-25    DCI DABRAFENIBUM + DCI TRAMETINIBUM
L01XE24    PONATINIB
L01XE26    CABOZANTINIBUM
L01XE27    IBRUTINIBUM
L01XE28    CERITINIBUM
L01XE31    NINTEDANIBUM (OFEV)
L01XE33    PALBOCICLIBUM
L01XE35    OSIMERTINIB
L01XE36    ALECTINIB
L01XE39    MIDOSTAURINUM
L01XE42    RIBOCICLIBUM
L01XE44    LORLATINIBUM
L01XE50    ABEMACICLIBUM
L01XE54    GILTERITINIB
L01XX19    IRINOTECANUM (ONIVYDE PEGYLATED LIPOSOMAL)
L01XX24    PEGASPARGASUM
L01XX27    ARSENICUM TRIOXIDUM
L01XX41    ERIBULINUM
L01XX42    PANOBINOSTATUM
L01XX44    AFLIBERCEPTUM
L01XX45    CARFILZOMIBUM
L01XX46    OLAPARIBUM
L01XX50    IXAZOMIB
L01XX52    VENETOCLAX
L01XX63    GLASDEGIB
L01XX71    TISAGENLECLEUCEL
L01XY02    PERTUZUMABUM + TRASTUZUMABUM
L020F    BUPROPIONUM
L022B    EPOETINUM ÎN ANEMIA ONCOLOGICĂ
L025C    CYPROTERONUM
L026C    TRASTUZUMABUM
L02BB04    ENZALUTAMIDUM
L02BB05    APALUTAMIDUM
L02BX03    ABIRATERONUM
L031C    ERLOTINIBUM
L033C    TRASTUZUMABUM
L034K    BOALĂ CRONICĂ INFLAMATORIE INTESTINALĂ
L037C    CETUXIMABUM
L038C    SORAFENIBUM
L039C    LEUPRORELINUM
L039M    ARTRITA IDIOPATICĂ JUVENILĂ SI BOALA STILL (FORME CU DEBUT JUVENIL SI LA ADULT) - AGENŢI BIOLOGICI: ADALIMUMABUM**1, ETANERCEPTUM**1, ABATACEPTUM**1, TOCILIZUMABUM**1, GOLIMUMABUM**1, ANAKINRA**1
L03AA14    LIPEGFILGRASTIMUM
L03AX03    VACCIN BCG
L040C    GOSERELINUM
L040M    ARTRITA PSORIAZICĂ – AGENŢI BIOLOGICI: ADALIMUMABUM**1 (ORIGINAL ŞI BIOSIMILAR), CERTOLIZUMABUM**1, ETANERCEPTUM**1 (ORIGINAL ŞI BIOSIMILAR), GOLIMUMABUM**1, INFLIXIMABUM**1 (ORIGINAL ŞI BIOSIMILAR), SECUKINUMABUM**1, IXEKIZUMABUM**1, GUSELKUMABUM**1Ω ŞI REMISIVE SINTETICE ŢINTITE (ts-DMARDs): TOFACITINIB**1Ω, UPADACITINIB**1, APREMILASTUM**1Ω
L041M    SPONDILOARTRITA AXIALĂ, INCLUZÂND SPONDILITA ANCHILOZANTĂ ȘI SPONDILOARTRITA AXIALĂ NONRADIOGRAFICĂ - AGENŢI BIOLOGICI: ADALIMUMABUM**1 (ORIGINAL ŞI BIOSIMILAR), CERTOLIZUMABUM**1, ETANERCEPTUM**1 (ORIGINAL ŞI BIOSIMILAR), GOLIMUMABUM**1, INFLIXIMABUM**1 (ORIGINAL ŞI BIOSIMILAR), SECUKINUMABUM**1, IXEKIZUMABUM**1Ω ȘI SINTETICI ȚINTIȚI: UPADACITINIBUM**1Ω
L042C    SUNITINIBUM
L043M    POLIARTRITA REUMATOIDĂ - AGENŢI BIOLOGICI: INFLIXIMABUM**1 (ORIGINAL ŞI BIOSIMILAR), ETANERCEPTUM**1 (ORIGINAL ŞI BIOSIMILAR), ADALIMUMABUM**1 (ORIGINAL ŞI BIOSIMILAR), GOLIMUMABUM**1, CERTOLIZUMABUM**1, RITUXIMABUM**1 (ORIGINAL ŞI BIOSIMILAR), TOCILIZUMABUM**1, ABATACEPTUM**1ŞI REMISIVE SINTETICE ŢINTITE: BARICITINIBUM**1, TOFACITINIBUM**1, UPADACITINIBUM**1, FILGOTINIBUM**1
L044L    PSORIAZIS CRONIC SEVER (ÎN PLĂCI) - AGENŢI BIOLOGICI ŞI TERAPII CU MOLECULE MICI CU ACŢIUNE INTRACELULARĂ
L047E    TRIPTORELINUM
L048C    FLUDARABINUM
L04AA03    IMUNOGLOBULINA ANTI-LIMFOCITE
L04AA10    SIROLIMUS
L04AA25-HPN    ECULIZUMABUM-HEMOGLOBINURIE PAROXISTICA NOCTURNA(HPN)
L04AA25-SHUa    ECULIZUMABUM-SINDROM HEMOLITIC UREMIC ATIPIC(SHUa)
L04AA43-HPN    RAVULIZUMABUM
L04AA43-SHUa    RAVULIZUMABUM
L04AB04-HS    ADALIMUMABUM
L04AB04-UV    ADALIMUMABUM
L04AC07    TOCILIZUMABUM (concentrația 162 mg)
L04AC08    CANAKINUMABUM
L04AC11    SILTUXIMABUM
L04AC19    SATRALIZUMABUM
L04AX02    TALIDOMIDUM
L04AX04    LENALIDOMIDUM
L04AX06    POMALIDOMIDUM
L04AX08    DARVADSTROCEL
L050C    INTERFERONUM ALFA 2A
LB01B    HEPATITĂ CRONICĂ ŞI CIROZĂ HEPATICĂ CU VIRUS VHB
M003M    OSTEOPOROZA - ACIDUM ALENDRONICUM**; ACIDUM RISEDRONICUM**; ACIDUM ZOLENDRONICUM**; COMBINAŢII (ACIDUM ALENDRONICUM + COLECALCIFEROLUM)**; DENOSUMABUM(Prolia)**; TERIPARATIDUM**(original si biosimilar)
M01AE52    COMBINATII(NAPROXENUM+ESOMEPRAZOLUM)
M03BX04    TOLPERISONUM
M05BX04    DENOSUMAB (PROLIA)
M05BX04    DENOSUMAB (XGEVA)
M05BX05    BUROSUMABUM
M09AX01    ACIDUM HIALURONICUM
M09AX03    ATALUREN
M09AX07    NUSINERSENUM
M09AX09    ONASEMNOGEN ABEPARVOVEC
M09AX10    RISDIPLAMUM
N001F    MEMANTINUM
N0020F    ATOMOXETINUM
N0021F    METHYLFENIDATUM
N0026G    ROTIGOTINUM
N002F    MILNACIPRANUM
N003F    OLANZAPINUM
N004F    RISPERIDONUM
N005F    QUETIAPINUM
N006F    AMISULPRIDUM
N007F    ARIPIPRAZOLUM
N008F    CITALOPRAMUM
N009F    ESCITALOPRAMUM
N010F    TRAZODONUM
N011F    TIANEPTINUM
N012F    LAMOTRIGINUM
N013F    VENLAFAXINUM
N014F    DULOXETINUM
N015F    FLUPENTIXOLUM
N016F    CLOZAPINUM
N017F    SERTINDOL
N018F    ZIPRASIDONUM
N019F    ZUCLOPENTHIXOLUM
N020G    DONEPEZILUM
N021G    RIVASTIGMINUM
N022G    GALANTAMINUM
N024G    RILUZOLUM
N025G    PROTOCOL DE TRATAMENT ÎN DUREREA NEUROPATĂ
N026F    HIDROLIZAT DIN CREIER DE PORCINĂ
N028F    PALIPERIDONUM
N02CD02    GALCANEZUMABUM
N030C    DURERE CRONICĂ DIN CANCER
N032G    PREGABALINUM
N03AX17    STIRIPENTOLUM
N03AX23    BRIVARACETAMUM
N04BC07    APOMORFINUM
N06AX27    ESKETAMINUM
N06BX13    IDEBENONUM
N07XX06    TETRABENAZINUM
N07XX07    FAMPRIDINE
N07XX11    PITOLISANTUM
N07XX12    PATISIRANUM
NG01G    PROTOCOL PENTRU TERAPIA MEDICAMENTOASĂ CRONICĂ A EPILEPSIEI
R001E    ERDOSTEINUM
R03AC13    FORMOTEROLUM
R03AC18    INDACATEROLUM
R03AL04    COMBINATII(INDACATEROLUM+GLICOPIRONIUM)
R03AL05    COMBINAȚII (ACLIDINIUM BROMIDUM + FORMOTEROLUM FUMARAT)
R03AL06    COMBINATII(TIOTROPIUM+OLADATEROLUM)
R03BB06    GLICOPIRONIUM
R03DX05    OMALIZUMABUM
R03DX10    BENRALIZUMABUM
R07AX02    IVACAFTORUM
R07AX30    LUMACAFTORUM+IVACAFTORUM
R07AX32    IVACAFTORUM+TEZACAFTORUM+ELEXACAFTORUM
S01EE05    TAFLUPROSTUM
S01LA04    RANIBIZUMABUM
S01LA05    AFLIBERCEPTUM
S01LA06    BROLUCIZUMABUM
S01XA18    CICLOSPORINUM
V001D    DEFEROXAMINUM
V002D    DEFERASIROXUM
V003D    SEVELAMER
V004N    AMINOACIZI, INCLUSIV COMBINAŢII CU POLIPEPTIDE
V03AE05    OXIHIDROXID SUCROFERIC`;

interface ProtocolEntry {
  code: string;
  title: string;
  pdfUrl: string;
}

function parseFormareMedicalaList(): ProtocolEntry[] {
  const lines = rawList.trim().split('\n');
  const protocols: ProtocolEntry[] = [];

  for (const line of lines) {
    // Split by multiple spaces (4+ spaces as delimiter)
    const match = line.match(/^([A-Z0-9\-]+)\s{2,}(.+)$/);

    if (match) {
      const code = match[1].trim();
      const title = match[2].trim();
      const pdfUrl = `https://www.formaremedicala.ro/media/protocoale/${code}.pdf`;

      protocols.push({ code, title, pdfUrl });
    }
  }

  return protocols;
}

const protocols = parseFormareMedicalaList();

console.log(`Parsed ${protocols.length} protocols from FormareMedicala.ro list`);

// Group by first letter
const byLetter: Record<string, number> = {};
protocols.forEach(p => {
  const letter = p.code[0];
  byLetter[letter] = (byLetter[letter] || 0) + 1;
});

console.log('\nDistribution by first letter:');
Object.entries(byLetter).sort().forEach(([letter, count]) => {
  console.log(`  ${letter}: ${count} protocols`);
});

// Save to JSON
const outputPath = 'data/formaremedicala-complete-list.json';
writeFileSync(outputPath, JSON.stringify(protocols, null, 2));
console.log(`\n✓ Saved complete list to ${outputPath}`);

// Sample
console.log('\nSample protocols (first 10):');
protocols.slice(0, 10).forEach(p => {
  console.log(`  ${p.code}: ${p.title.substring(0, 80)}`);
});

console.log(`\nTotal protocols: ${protocols.length}`);
